/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedWorkforceRouteImport } from './routes/_authenticated/workforce'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedProgramRouteImport } from './routes/_authenticated/program'
import { Route as AuthenticatedOrganizationalRouteImport } from './routes/_authenticated/organizational'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedExecutivesRouteImport } from './routes/_authenticated/executives'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultantsRouteImport } from './routes/_authenticated/consultants'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRequestsNewRouteImport } from './routes/_authenticated/requests.new'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests.$id'

const AuthenticatedWorkforceRoute = AuthenticatedWorkforceRouteImport.update({
  id: '/_authenticated/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/_authenticated/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgramRoute = AuthenticatedProgramRouteImport.update({
  id: '/_authenticated/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationalRoute =
  AuthenticatedOrganizationalRouteImport.update({
    id: '/_authenticated/organizational',
    path: '/organizational',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/_authenticated/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/_authenticated/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExecutivesRoute = AuthenticatedExecutivesRouteImport.update({
  id: '/_authenticated/executives',
  path: '/executives',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsultantsRoute =
  AuthenticatedConsultantsRouteImport.update({
    id: '/_authenticated/consultants',
    path: '/consultants',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestsNewRoute =
  AuthenticatedRequestsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRequestsRoute,
  } as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AuthenticatedAdminRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/executives': typeof AuthenticatedExecutivesRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/organizational': typeof AuthenticatedOrganizationalRoute
  '/program': typeof AuthenticatedProgramRoute
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AuthenticatedAdminRoute
  '/consultants': typeof AuthenticatedConsultantsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/executives': typeof AuthenticatedExecutivesRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/organizational': typeof AuthenticatedOrganizationalRoute
  '/program': typeof AuthenticatedProgramRoute
  '/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/new': typeof AuthenticatedRequestsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/consultants': typeof AuthenticatedConsultantsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/executives': typeof AuthenticatedExecutivesRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/organizational': typeof AuthenticatedOrganizationalRoute
  '/_authenticated/program': typeof AuthenticatedProgramRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRouteWithChildren
  '/_authenticated/workforce': typeof AuthenticatedWorkforceRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/requests/new': typeof AuthenticatedRequestsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/consultants'
    | '/dashboard'
    | '/executives'
    | '/governance'
    | '/knowledge'
    | '/organizational'
    | '/program'
    | '/requests'
    | '/workforce'
    | '/requests/$id'
    | '/requests/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/consultants'
    | '/dashboard'
    | '/executives'
    | '/governance'
    | '/knowledge'
    | '/organizational'
    | '/program'
    | '/requests'
    | '/workforce'
    | '/requests/$id'
    | '/requests/new'
  id:
    | '__root__'
    | '/_authenticated/admin'
    | '/_authenticated/consultants'
    | '/_authenticated/dashboard'
    | '/_authenticated/executives'
    | '/_authenticated/governance'
    | '/_authenticated/knowledge'
    | '/_authenticated/organizational'
    | '/_authenticated/program'
    | '/_authenticated/requests'
    | '/_authenticated/workforce'
    | '/_authenticated/requests/$id'
    | '/_authenticated/requests/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConsultantsRoute: typeof AuthenticatedConsultantsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExecutivesRoute: typeof AuthenticatedExecutivesRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedOrganizationalRoute: typeof AuthenticatedOrganizationalRoute
  AuthenticatedProgramRoute: typeof AuthenticatedProgramRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRouteWithChildren
  AuthenticatedWorkforceRoute: typeof AuthenticatedWorkforceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/workforce': {
      id: '/_authenticated/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AuthenticatedWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/program': {
      id: '/_authenticated/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof AuthenticatedProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizational': {
      id: '/_authenticated/organizational'
      path: '/organizational'
      fullPath: '/organizational'
      preLoaderRoute: typeof AuthenticatedOrganizationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/executives': {
      id: '/_authenticated/executives'
      path: '/executives'
      fullPath: '/executives'
      preLoaderRoute: typeof AuthenticatedExecutivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consultants': {
      id: '/_authenticated/consultants'
      path: '/consultants'
      fullPath: '/consultants'
      preLoaderRoute: typeof AuthenticatedConsultantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests/new': {
      id: '/_authenticated/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthenticatedRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRequestsRoute
    }
  }
}

interface AuthenticatedRequestsRouteChildren {
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedRequestsNewRoute: typeof AuthenticatedRequestsNewRoute
}

const AuthenticatedRequestsRouteChildren: AuthenticatedRequestsRouteChildren = {
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
  AuthenticatedRequestsNewRoute: AuthenticatedRequestsNewRoute,
}

const AuthenticatedRequestsRouteWithChildren =
  AuthenticatedRequestsRoute._addFileChildren(
    AuthenticatedRequestsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConsultantsRoute: AuthenticatedConsultantsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExecutivesRoute: AuthenticatedExecutivesRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedOrganizationalRoute: AuthenticatedOrganizationalRoute,
  AuthenticatedProgramRoute: AuthenticatedProgramRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRouteWithChildren,
  AuthenticatedWorkforceRoute: AuthenticatedWorkforceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
